version: '3.8'

services:
  ride-service:
    build:
      context: ./services/ride-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  reservation-service:
    build:
      context: ./services/reservation-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "4000:4000"
    environment:
      QUARKUS_HTTP_PORT: "4000"
      QUARKUS_DATASOURCE_REACTIVE_URL: "postgresql://postgres:5432/reservations"
      QUARKUS_DATASOURCE_USERNAME: "postgres"
      QUARKUS_DATASOURCE_PASSWORD: "alen123"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "alen123"
      POSTGRES_DB: "reservations"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
