version: '3.8'

services:
  ride-service:
    build:
      context: ./services/ride-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  reservation-service:
    build:
      context: ./services/reservation-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_RESERVATIONS_DB}"
      QUARKUS_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      QUARKUS_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_RESERVATIONS_DB}
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
