version: '3.8'

services:
  ride-service:
    build:
      context: ./services/ride-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      activemq:
        condition: service_healthy
    restart: on-failure

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure

  reservation-service:
    build:
      context: ./services/reservation-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "4000:4000"
    environment:
      QUARKUS_HTTP_PORT: "4000"
      QUARKUS_DATASOURCE_REACTIVE_URL: "postgresql://postgres:5432/reservations"
      QUARKUS_DATASOURCE_USERNAME: "postgres"
      QUARKUS_DATASOURCE_PASSWORD: "alen123"
      QUARKUS_ARTEMIS_URL: "tcp://activemq:61616"
    depends_on:
      activemq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "alen123"
      POSTGRES_DB: "reservations"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  activemq:
    image: apache/activemq-artemis
    container_name: activemq_artemis
    restart: always
    ports:
      - "61616:61616"  # for JMS
      - "5672:5672"    # for AMQP
      - "8161:8161"    # for Web Console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: artemis
      ACTIVEMQ_ADMIN_PASSWORD: artemis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      retries: 5
      start_period: 10s
      
volumes:
  postgres_data:

networks:
  default:
    driver: bridge
