server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Only scrape user-service logs
  - job_name: user-service
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '.*user-service.*'
        action: keep
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          service: user-service
          __path__: /var/lib/docker/containers/*/*.log