name: Ride CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print current directory
      run: pwd

    - name: List files
      run: ls -la

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24'

    - name: Change directory to ride-service
      run: cd services/ride-service

    - name: Install dependencies
      working-directory: services/ride-service
      run: go mod download

    - name: Run tests
      working-directory: services/ride-service
      run: go test -v ./...
