name: User CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3:latest
        ports:
          - 8080:8080
        options: >-
          --entrypoint "sqlite3"
          --command "CREATE DATABASE test_db;" # Command to create a test database if needed

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: services/user-service

    - name: Run database migrations
      run: npm run migrate 

    - name: Run tests
      run: npm run test
      working-directory: services/user-service
